name: Check Owner Key in YML Files

on:
 pull_request:
    paths:
      - '**.yml'

jobs:
 check-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Check Owner Key
        run: |
          STATUS=0
          FILES=$(find . -name "*.yml" -not -path "./.github/workflows/*")
          for file in $FILES; do
            echo "Checking file: $file"
            python .github/workflows/check_owner.py "$file" || STATUS=1
          done
          if [ $STATUS -ne 0 ]; then
            echo "One or more YAML files do not contain the required 'Owner' key."
            exit 1
          fi

